### ISSUE TITLE
Incorrect file permissions in 2.8.0

### ISSUE THREAD

**Issue by CvX** [mikel/mail#1489] opened 2022-05-17 14:54 UTC
Some files in 2.8.0.rc1 release are not world-readable: (notice `elements.rb`, `fields.rb`, `indifferent_hash.rb`)

```
-rw-r--r--@  1 cvx  staff   3481 Apr 22 02:41 attachments_list.rb
-rw-r--r--@  1 cvx  staff   9545 Apr 22 02:41 body.rb
-rw-r--r--@  1 cvx  staff   1781 Apr 22 02:41 configuration.rb
-rw-r--r--@  1 cvx  staff   2472 Apr 22 02:41 constants.rb
drwxr-xr-x  14 cvx  staff    448 May 17 16:51 elements
-rw-r-----@  1 cvx  staff    960 Apr 22 02:41 elements.rb
drwxr-xr-x  10 cvx  staff    320 May 17 16:51 encodings
-rw-r--r--@  1 cvx  staff   9792 Apr 22 02:41 encodings.rb
-rw-r--r--@  1 cvx  staff    573 Apr 22 02:41 envelope.rb
-rw-r--r--@  1 cvx  staff   8885 Apr 22 02:41 field.rb
-rw-r--r--@  1 cvx  staff   2077 Apr 22 02:41 field_list.rb
drwxr-xr-x  41 cvx  staff   1312 May 17 16:51 fields
-rw-r-----@  1 cvx  staff   2244 Apr 22 02:41 fields.rb
-rw-r--r--@  1 cvx  staff   7528 Apr 22 02:41 header.rb
-rw-r-----@  1 cvx  staff   3874 Apr 22 02:41 indifferent_hash.rb
-rw-r--r--@  1 cvx  staff   8346 Apr 22 02:41 mail.rb
drwxr-xr-x   4 cvx  staff    128 May 17 16:51 matchers
-rw-r--r--@  1 cvx  staff  67251 Apr 22 02:41 message.rb
drwxr-xr-x   5 cvx  staff    160 May 17 16:51 multibyte
-rw-r--r--@  1 cvx  staff   3563 Apr 22 02:41 multibyte.rb
drwxr-xr-x   4 cvx  staff    128 May 17 16:51 network
-rw-r--r--@  1 cvx  staff    836 Apr 22 02:41 network.rb
-rw-r--r--@  1 cvx  staff    446 Apr 22 02:41 parser_tools.rb
drwxr-xr-x  34 cvx  staff   1088 May 17 16:51 parsers
-rw-r--r--@  1 cvx  staff    522 Apr 22 02:41 parsers.rb
-rw-r--r--@  1 cvx  staff   3124 Apr 22 02:41 part.rb
-rw-r--r--@  1 cvx  staff   3374 Apr 22 02:41 parts_list.rb
-rw-r--r--@  1 cvx  staff   1410 Apr 22 02:41 smtp_envelope.rb
-rw-r--r--@  1 cvx  staff  16176 Apr 22 02:41 utilities.rb
drwxr-xr-x   3 cvx  staff     96 May 17 16:51 values
-rw-r--r--@  1 cvx  staff    235 Apr 22 02:41 version.rb
-rw-r--r--@  1 cvx  staff    655 Apr 22 02:41 yaml.rb
```

This wasn't the case in previous releases:

```
# 2.7.1
-rw-r--r--@  1 cvx  staff   3590 Oct 13  2018 attachments_list.rb
-rw-r--r--@  1 cvx  staff   9745 Oct 13  2018 body.rb
-rw-r--r--@  1 cvx  staff   1461 Oct 13  2018 check_delivery_params.rb
-rw-r--r--@  1 cvx  staff   1781 Oct 13  2018 configuration.rb
-rw-r--r--@  1 cvx  staff   1792 Oct 13  2018 constants.rb
drwxr-xr-x   4 cvx  staff    128 May 17 16:39 core_extensions
drwxr-xr-x  14 cvx  staff    448 May 17 16:39 elements
-rw-r--r--@  1 cvx  staff    960 Oct 13  2018 elements.rb
drwxr-xr-x  10 cvx  staff    320 May 17 16:39 encodings
-rw-r--r--@  1 cvx  staff  10711 Oct 13  2018 encodings.rb
-rw-r--r--@  1 cvx  staff    658 Oct 13  2018 envelope.rb
-rw-r--r--@  1 cvx  staff   9511 Oct 13  2018 field.rb
-rw-r--r--@  1 cvx  staff    867 Oct 13  2018 field_list.rb
drwxr-xr-x  35 cvx  staff   1120 May 17 16:39 fields
-rw-r--r--@  1 cvx  staff   2244 Oct 13  2018 fields.rb
-rw-r--r--@  1 cvx  staff   9235 Oct 13  2018 header.rb
-rw-r--r--@  1 cvx  staff   3874 Oct 13  2018 indifferent_hash.rb
-rw-r--r--@  1 cvx  staff   8346 Oct 13  2018 mail.rb
drwxr-xr-x   4 cvx  staff    128 May 17 16:39 matchers
-rw-r--r--@  1 cvx  staff  68178 Oct 13  2018 message.rb
drwxr-xr-x   5 cvx  staff    160 May 17 16:39 multibyte
-rw-r--r--@  1 cvx  staff   3766 Oct 13  2018 multibyte.rb
drwxr-xr-x   4 cvx  staff    128 May 17 16:39 network
-rw-r--r--@  1 cvx  staff    836 Oct 13  2018 network.rb
-rw-r--r--@  1 cvx  staff    446 Oct 13  2018 parser_tools.rb
drwxr-xr-x  34 cvx  staff   1088 May 17 16:39 parsers
-rw-r--r--@  1 cvx  staff    681 Oct 13  2018 parsers.rb
-rw-r--r--@  1 cvx  staff   3230 Oct 13  2018 part.rb
-rw-r--r--@  1 cvx  staff   2003 Oct 13  2018 parts_list.rb
-rw-r--r--@  1 cvx  staff   8570 Oct 13  2018 utilities.rb
drwxr-xr-x   3 cvx  staff     96 May 17 16:39 values
-rw-r--r--@  1 cvx  staff    233 Oct 13  2018 version.rb
drwxr-xr-x   4 cvx  staff    128 May 17 16:39 version_specific
```

…and makes the gem unusable in some setups:

```
LoadError: cannot load such file -- /usr/local/lib/ruby/gems/2.7.0/gems/mail-2.8.0.rc1/lib/mail/indifferent_hash.rb
```

Can you re-release rc1 with corrected permissions as rc2?

**Comment by djpate** [comment] 2022-10-12 18:00
Any updates on this?

**Comment by rmehner** [comment] 2022-12-06 14:23
We've also been bitten by this. We've downgraded to 2.7.1 for now. Another workaround was to fix the permissions ourselves within the docker container. A bit hacky, but works.

**Comment by rgaufman** [comment] 2022-12-09 00:57
Had to downgrade to  2.7.1 also :(

**Comment by themilkman** [comment] 2022-12-09 09:49
Also run in troubles with this in context of Devise::Mailer. Chmod'ing files helped.

**Comment by akilamunasinghe** [comment] 2022-12-12 23:06
We ran into the same issue and I have trouble downgrading as it is a dependency for later versions of `actionmailer`.

**Comment by sengi** [comment] 2022-12-14 11:19
Oh no, sorry for causing all that crossref spam 🫣 (I'll try [this workaround](https://github.com/orgs/community/discussions/23123#discussioncomment-3239240) to avoid it in future.)

**Comment by mikel** [comment] 2022-12-14 21:49
Yes, let's get this fixed.  Thanks @eval

**Comment by FelipeAsenjo** [comment] 2022-12-27 19:36
Hello!

Somehow i avoid the problem by not using the "-T" flag for avoiding testing libraries, obviously is not an ideal solution but it might be a clue to help find the problem.

**Comment by seoanezonjic** [comment] 2023-01-10 16:17
I think that this problem is not fully resolved. I've the following with the 2.8.0 version in rubygems:
![mail_gem](https://user-images.githubusercontent.com/4126037/211604205-6c8e8f01-d514-4c55-80d7-adab755962d0.png)
 The indifferent_hash.rb breaks in my aws deploy when puma server boots.
Thank you in advance
Pedro Seoane

**Comment by ralph** [comment] 2023-01-10 16:18
@seoanezonjic 2.8.0 is the published version with the broken file permissions we're talking about. There is no published fix yet.

**Comment by seoanezonjic** [comment] 2023-01-10 16:21
Sorry, I thougth that previous rc releases contained the bug and the 2.8.0 fixed this. I suppose that use the 2.7.1 version is the easy way to avoid this problem.

**Comment by seoanezonjic** [comment] 2023-01-10 16:38
Yeah, my problem that this broken version is used for several gems in rails and I not see how to manipulate the Gemfile to obtain the 2.7.1 in the deploy process.

**Comment by benlangfeld** [comment] 2023-01-10 16:43
Yep, hundreds of people suffered similar problems because of this problem, but only two people in the world can fix it because the release process is not automated.

**Comment by brunnopleffken** [comment] 2023-01-10 18:31
This issue broke my Ruby on Rails app in production environment. The two lines below solved it:

```bash
cd /var/www/[project_name]/vendor/bundle/ruby/3.2.0/gems/mail-2.8.0/lib/mail
chmod 644 indifferent_hash.rb fields.rb elements.rb 
```

These three files aren't readable.

This is a **serious** issue because `mail` is a dependency of Rails' `action mailer` and `actionmailbox` running in thousands of Rails apps out there.

**Comment by ralph** [comment] 2023-01-10 18:35
You can add this to your Gemfile to avoid the faulty release:

```ruby
# FIXME:
# mail v2.8.0 shipped with faulty file permissions, see: https://github.com/mikel/mail/issues/1489.
# Remove the following line once a fixed release is available:
gem 'mail', '!= 2.8.0'
```

**Comment by ssunday** [comment] 2023-01-10 18:56
Can 2.8.0 please be yanked, at least?

**Comment by pedantic-git** [comment] 2023-01-10 19:01
Just dropping my vote for not yanking 2.8.0 - it's not a security or legal issue and it works OK with the workarounds described above (for me it was [a one-line change to my test Dockerfile](https://github.com/fishpercolator/name.pn/commit/3ba304bf9e2fa07d20814855a1e566a326b5f0ac), for example) and there are already downstream gems that depend on it. I'm thinking if someone has the power to yank 2.8.0 they also have the power to release 2.8.1, which seems to me like a better solution.

**Comment by ssunday** [comment] 2023-01-10 19:05
I don't think a gem that requires work arounds to be functional should be allowed to be an active release, but that's my opinion. Or if it does, there should be a notification on install or documentation besides this thread. 

But +1 to the power to yank is also the power to release... which would be great 😓

**Comment by rgaufman** [comment] 2023-01-11 00:20
+1 for yanking, this is breaking prod unexpectedly for all rails users and should be considered critical and yanked until a fixed version can be released.

**Comment by benlangfeld** [comment] 2023-01-11 17:24
> +1 for yanking, this is breaking prod unexpectedly for all rails users and should be considered critical and yanked until a fixed version can be released.

Releasing a fixed version is no more difficult than yanking, as was discussed above. Everyone here agrees on the criticality, but that is worthless because none of us have the ability to cut a release. Someone who knows the maintainer personally needs to bring it to his attention.

**Comment by rgaufman** [comment] 2023-01-11 20:41
This has unexpectedly killed the production systems of many critical and non-critical systems. This is a nasty bug that passes through CI and testing, so it really catches people off guard and it is not obvious to find the cause or implement the workaround - especially while being faced with a sudden barrage of health notification and customer complaints.

For those of us impacted by this, the damage is done and we know how to prevent further downtime. But others are killing their production systems every minute this release is allowed to remain.

Even if this saves a single more production environment from being killed, it is worth yanking in my humble opinion. Even if there is a new release, it is still worth yanking at the risk of someone installing this version by accident.

**Comment by Nakilon** [comment] 2023-01-12 06:17
That's an interesting bug. It's not fully the gem's fault, it's unix. I'm not sure anyone has tests for their libraries CI to run them by a user different from the one who deploys on the test machine right before that.

**Comment by themilkman** [comment] 2023-01-12 06:37
The really important question is imho: How can it be that such an important gem is so under-maintained that there is no new release within at least a week :-/

**Comment by frenkel** [comment] 2023-01-12 08:17
> The really important question is imho: How can it be that such an important gem is so under-maintained that there is no new release within at least a week :-/

Because nobody is paying for it.

**Comment by themilkman** [comment] 2023-01-12 08:56
> Because nobody is paying for it.

Sure and I didn't meant to offense someone, but there are several good reasons to have a second person with rubygems.org release permissions and the will to do so. Money is obviously a thing regarding keep the development ongoing, but issues like this are not that time consuming to resolve. Again, no offense to Mikel or anyone else involved, quite the opposite: Thanks for the work already invested in this gem!! :heart: 
Nevertheless... the issue is problematic.

**Comment by benlangfeld** [comment] 2023-01-12 12:38
> This has unexpectedly killed the production systems of many critical and non-critical systems. This is a nasty bug that passes through CI and testing

How is that possibly true? That seems like a serious defect in your software delivery procedures. The consequences of this bug should be limited to failures to build new versions of your software; if you suffered more than that, you should look into software packaging best practices and I'd be happy to provide more specific advice in practice if you want to reach out.

**Comment by stell** [comment] 2023-01-12 13:00
@benlangfeld @rgaufman I agree with Ben. Our build process was disrupted, but it had nothing to do with delivery and testing. After we [got the bug under control](https://github.com/sj26/mailcatcher/issues/528#issuecomment-1339116112) so far, all other processes ran unaffected. It did not and should not affect systems in production at any time.

**Comment by rgaufman** [comment] 2023-01-12 15:45
@stell @benlangfeld Very easily. Running bundle update does not trigger the bug, so the developer has no idea this will kill production. Once a commit is done, the CI systems often run in isolated environments and install specific versions of Ruby for testing, so this passes through many CI systems including ours which uses github-actions.

In production, if the company standardised on a Ruby version, it can be a deb package instead of RBenv or RVM (ours is build with jemalloc which reduces ram usage), so in that situation, the bug is not triggerable until the code hits production.

**Comment by benlangfeld** [comment] 2023-01-12 15:49
> @stell @benlangfeld Very easily. Running bundle update does not trigger the bug, so the developer has no idea this will kill production. Once a commit is done, the CI systems often run in isolated environments and install specific versions of Ruby for testing, so this passes through many CI systems including ours which uses github-actions.
> 
> In production, if the company standardised on a Ruby version, it can be a deb package instead of RBenv or RVM (ours is build with jemalloc which reduces ram usage), so in that situation, the bug is not triggerable until the code hits production.
>
> With due respect, I am not asking for advice on how to redesign our production systems, I am asking for the gem version to be yanked as it kills build systems, can kill production systems, requires workarounds, etc - it should just not exist even if a new version is released.

@rgaufman I maintain that this is indicative of a serious bug in your pipeline. A robust deployment pipeline would not permit the propagation of this issue to a production system. While this bug should never have been shipped, it was and others will be, and your pipeline has to be resilient to this kind of negative external influence. Rejecting advice is all well and good, but I'd still encourage you to reflect on why that happened to you and not to others.

**Comment by rgaufman** [comment] 2023-01-12 15:50
@benlangfeld Will do and I'd still encourage you to reflect on whether this gem version should be yanked or not. I maintain that it should be yanked.

**Comment by benlangfeld** [comment] 2023-01-12 16:10
> @benlangfeld Will do and I'd still encourage you to reflect on whether this gem version should be yanked or not. I maintain that it should be yanked.

Dude, it doesn't matter one ounce what you or I think about whether the gem should be yanked or not; we could debate that all day and it wouldn't change anything. It matters who knows/works with @mikel and can bring to his attention the breadth of the impact of this issue and the urgency in correcting it, be that by way of him finding time to address it personally or by nominating additional maintainers who could take care of it.

**Comment by rgaufman** [comment] 2023-01-12 16:35
My point is yanking the release appears to be the quickest immediate solution that should require the least amount of time. I appreciate @mikel has many priorities and finding the time to sit down to look at this can be challenging. While yanking the release can be done from a mobile phone while walking to the kitchen for a cup of coffee.

Afterwards, I agree, possibly looking at additional maintainers, or changes to the release process, fixing this for the next release, etc, etc can all be looked at, really in any order.

**Comment by rgaufman** [comment] 2023-01-12 18:39
Sure, release 2.8.1, no arguments there, but I don't see the point of keeping a broken release. Broken releases should be yanked, it is best practice.

**Comment by jeremy** [comment] 2023-01-12 18:50
Fixed in #1555. Please give [2.8.0.1.rc1](https://rubygems.org/gems/mail/versions/2.8.0.1.rc1) a try.

**Closed by jeremy** 2023-01-12 18:50 UTC

**Comment by ralph** [comment] 2023-01-12 19:36
[2.8.0.1](https://rubygems.org/gems/mail/versions/2.8.0.1) is released and works flawlessly for me.

**Comment by stillhart** [comment] 2023-01-13 09:26
Thank you very much for the new release. I still find it really interesting that rubygems and bundler do respect file permissions within packed gems. I really did not know that and wonder how much that feature is actively used in production.
