### ISSUE TITLE
Mail::AddressListsParser can not parse

### ISSUE THREAD

**Issue by ckarbass** [mikel/mail#778] opened 2014-08-09 01:32 UTC
Looks like the parser isn't handling ñ or non english characters on Ruby 2.0.0 Rails 4

**Comment by bonsaiben** [comment] 2015-01-11 01:48
Also appears not to be able to parse Japanese characters.

**Comment by bf4** [comment] 2015-01-12 01:30
cc @bpot

**Comment by bpot** [comment] 2015-01-12 03:06
I believe this is expected behavior -- the parser expects all headers to only contain ASCII characters. It assumes non-ascii characters will be encoded as specified in [rfc2047](https://www.ietf.org/rfc/rfc2047.txt). For example: https://github.com/mikel/mail/blob/master/spec/mail/encodings_spec.rb#L93

However, it looks like there are now some RFCs around the use of non-ascii characters in email headers  that are finding being adopted: http://en.wikipedia.org/wiki/International_email#Overview_and_Framework_for_Internationalized_Email

I can take a look at what changes would need to be made to the parser to support 'international emails'.

@ckarbass @bonsaiben Could you provide examples of failing emails and the version of the mail gem you are using? Thanks!

**Comment by jeremy** [comment] 2017-05-17 05:01
Fixed by #1103

**Closed by jeremy** 2017-05-17 05:01 UTC
