### ISSUE TITLE
charset disappears in Message class for multipart

### ISSUE THREAD

**Issue by dragosmiron** [mikel/mail#1183] opened 2017-12-13 17:20 UTC
Hi, there is this line in 2.6 stable that disappeared in 2.7 and there are errors because of it
https://github.com/mikel/mail/blob/2-6-stable/lib/mail/message.rb#L2074

Basically, when adding parts to message, say text and html, the first will succeed, because it takes the charset from message, but then `add_boundary` makes the `def charset` method return nil for next call.
Second part will get a nil charset, that results in an error when trying to call the `encoded` method.
It took me a quite a while to debug actionmailer + mail gem for this.
Any reason why the line I pointed out disappeared? It works when i added it back.

**Comment by jeremy** [comment] 2017-12-13 20:35
Good opportunity to check `git blame` to see which commit removed it and trace that back to the pull request responsible 👍

**Comment by dragosmiron** [comment] 2017-12-14 09:49
And the resolution is? Does it need to go back?

**Comment by dragosmiron** [comment] 2017-12-14 13:14
i am a bit confused because 2.7 stable also contains it . `master` doesn't have it, I thought master branch is "the lastest" branch.

**Comment by jeremy** [comment] 2017-12-14 19:02
The resolution is up to you to discover, @dragosmiron. `git blame` is how to track it down. You can review the git history to see exactly what happened, by whom, and for what reason.

**Comment by jeremy** [comment] 2018-04-18 01:53
Thanks @ahorek! Thoughts on this issue @kirikak2?

**Comment by kirikak2** [comment] 2018-04-20 02:33
Thanks for reply. I'm considering this issue. Please wait for a few days.

**Comment by kirikak2** [comment] 2018-06-05 11:46
@dragosmiron Sorry, for late response.
Can you show the sample case which reproduce it?
I tried. but I could not reproduce in my environment.

**Comment by jeremy** [comment] 2018-12-19 02:08
Reported at #1299 and fixed by #1300.

**Closed by jeremy** 2018-12-19 02:08 UTC
