### ISSUE TITLE
BCC Header-Field missing in #encoded. Mail is sent without BCC recipients.

### ISSUE THREAD

**Issue by Flauschbaellchen** [mikel/mail#1138] opened 2017-08-08 10:58 UTC
```ruby
Mail.new(subject: "test", body: "test", bcc: ["bcc@example.com"]).encoded
```
Returns: 
```
Date: Tue, 08 Aug 2017 12:46:22 +0200
Message-ID: <5989967e448e6_1dd880dbd0604e@yuffie.mail>
Subject: test
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
```
Which misses the BCC header field.

Mail is sent without BCC within Rails.
Round tripping the BCC field is not possible anymore, too.

I'm using the latest master branch within Rails:
```
rails (5.0.5)
mail (2.7.0.rc1 f0dbe48)
```

Rails Test-Mailer:
```ruby
class TestMailer < ApplicationMailer
  def send_test_mail
    sent_mail = mail(
      from: "from@example.com",
      to: "to@example.com",
      cc: ["cc@example.com"],
      bcc: ["bcc@example.com"],
      subject: "Test",
      date: Time.now)

    sent_mail.bcc #=> ["bcc@example.com"]
    Mail.new(sent_mail.encoded).bcc #=> nil
  end
end
```
Mail is sent without BCC:
```
Date: Tue, 08 Aug 2017 12:55:45 +0200
From: from@example.com
To: to@example.com
Cc: cc@example.com
Message-ID: <598998b14a726_1dd880dbd060567@yuffie.mail>
Subject: Test
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Test Content
```

**Comment by jeremy** [comment] 2017-08-08 15:58
> all with BCC are somehow ignored.

BCC fields are used as SMTP recipients. They aren't included in the mail message itself.  #426.

Set `mail.bcc.include_in_headers = true` to override this and include the BCC field anyway, anticipating that a downstream MTA will strip the fields instead. #872.

Duplicate of #1006

**Closed by jeremy** 2017-08-08 15:58 UTC

**Comment by thallada** [comment] 2019-02-25 18:31
It's `mail[:bcc].include_in_headers = true` FYI.
