### ISSUE TITLE
The return valus of to/cc/bcc are toggled when nil is assigned

### ISSUE THREAD

**Issue by dnagir** [mikel/mail#881] opened 2015-05-26 23:28 UTC
```ruby
mail = Mail.new

mail.cc = nil
mail.cc # => []

mail.cc = nil
mail.cc # => nil

mail.cc = nil
mail.cc # => []
```

As you can see the return value toggles between empty array and `nil`.
This is very unpredictable behaviour and needs to be fixed to return a consistent value.

The mail version is 2.6.3.

**Comment by jeremy** [comment] 2015-09-30 05:36
It is weird for sure. Duplicate of https://github.com/mikel/mail/issues/822#issuecomment-60823251

**Closed by jeremy** 2015-09-30 05:36 UTC
