### ISSUE TITLE
Attachments corrupted (new in 2.6.4)

### ISSUE THREAD

**Issue by jetinsight** [mikel/mail#988] opened 2016-04-20 23:19 UTC
Sending pdfs - pretty standard stuff (mostly 1 attachment per email, ~200kb each)

`attachments[pdf_name] = { content: pdf_content_already_base64_encoded, encoding: 'base64' }`

Worked perfectly fine with 2.6.3. With 2.6.4, the base64 encoded attachment that is received by the SMTP server is different (and shorter) than what was passed in - and pdf is corrupt.

**Comment by jeremy** [comment] 2016-04-20 23:34
Thanks for the report, @jetinsight. Do you have some sample code that demonstrates the regression?

**Comment by dalibor** [comment] 2016-10-06 20:33
Hi @jeremy,

I can confirm this is a regression coming from this PR: https://github.com/mikel/mail/pull/874 that was merged in the last release.

The problem is that if you set `base64` encoding on a `Mail::Part` body it gets automatically changed to `quoted-printable` if longer than 998 chars. In that PR description it says: "RFC 2821 specifies that SMTP lines must not be longer than 1000 characters. In this case, quoted-printable or base64 should be used rather than 8bit or 7bit.", so the expectation is as long as the encoding is valid per that RFC (`base64` or `quoted-printable`), it will use the one that was selected instead of choosing one with the cost calculation.

Here is a spec to demonstrate the issue:

```ruby
require 'spec_helper'

describe "Attachment bug" do
  it "sets correct encoding when Mail and Mail::Part" do
    mail = Mail.new
    mail.body << Mail::Part.new.tap do |part|
      part.header[:content_disposition] = 'attachment; filename="unnamed"'
      part.content_type  = 'text/plain'
      # part.body          = 'a' * 998
      part.body          = 'a' * 999
      part.body.encoding = 'base64'
    end

    part_body_encoding = mail.to_s.scan(/Content-Transfer-Encoding: (.+)\r$/).last.first
    expect(part_body_encoding).to eq('base64')
  end

  it "sets correct encoding when Mail::Part only" do
    part = Mail::Part.new.tap do |part|
      part.header[:content_disposition] = 'attachment; filename="unnamed"'
      part.content_type  = 'text/plain'
      # part.body          = 'a' * 998
      part.body          = 'a' * 999
      part.body.encoding = 'base64'
    end

    part_body_encoding = part.to_s.scan(/Content-Transfer-Encoding: (.+)\r$/).last.first
    expect(part_body_encoding).to eq('base64')
  end
end
```

If you change the commented out line, it will pass and that was the old and expected behavior before that change was introduced.

The closest I could get without breaking other specs was the following, but it breaks polymorphism and the issue seems deeper on the relation 'chosen' vs 'preferred' encoding and I suspect it might require bigger refactoring by someone more familiar with the code-base.

```patch
--- a/lib/mail/encodings/transfer_encoding.rb
+++ b/lib/mail/encodings/transfer_encoding.rb
@@ -17,7 +17,7 @@ module Mail
       end
 
       def self.cost(str)
@@ -33,7 +33,9 @@ module Mail
       end
 
       def self.get_best_compatible(source_encoding, str)
-        if self.can_transport?(source_encoding) && self.compatible_input?(str)
+        source_encoding_class = Encodings.get_encoding(source_encoding)
+
+        if self.can_transport?(source_encoding) && source_encoding_class.compatible_input?(str)
```

Thanks!

**Comment by dalibor** [comment] 2017-02-27 11:11
@pushrax Could you maybe please check this out and provide feedback on the proposed solution above? The "RFC 2821 line length limits" fix causes corrupted attachments when using base64 encoding.

**Closed** 2017-10-23 23:49 UTC
Labels: Backport, Bug, Encoding, More Work Needed
